#!/usr/bin/perl -w
#
#  $Id$
#

open(CHANGELOG, "<../!Sunfish/ChangeLog");
$line = <CHANGELOG>;
$line =~ /^v(.\...).*/;
$version = $1;
close CHANGELOG;

open(CHANGELOG, "<../src/cmhg/sunfish");
while (<CHANGELOG>) {
  if (/help\-string\: Sunfish (.\...) .*/) {
    die "Sunfish version mismatch" if ($version ne $1);
  }
}
close CHANGELOG;

open(OUT,">Sunfish/RiscPkg/Control");

print OUT qq{Package: Sunfish
Priority: Optional
Section: Disc
Maintainer: Alex Waugh <alex\@alexwaugh.com>
Standards-Version: 0.1.0
Version: $version
Licence: Free
Description: An NFS client.
 Sunfish is an NFS client for RISC OS. It is implemented as both a normal
 filing system and an image filing system, and provides flexible configuration
 options. Sunfish supports both the NFS2 and NFS3 protocols, over UDP or TCP
 connections.
};

close OUT;

open(CHANGELOG, "<../!Moonfish/ChangeLog");
$line = <CHANGELOG>;
$line =~ /^v(.\...).*/;
$version = $1;
close CHANGELOG;

open(CHANGELOG,"<../src/cmhg/moonfish");
while (<CHANGELOG>) {
  if (/help\-string\: Moonfish (.\...) .*/) {
    die "Moonfish version mismatch" if ($version ne $1);
  }
}
close CHANGELOG;

open(OUT,">Moonfish/RiscPkg/Control");

print OUT qq{Package: Moonfish
Priority: Optional
Section: Disc
Maintainer: Alex Waugh <alex\@alexwaugh.com>
Standards-Version: 0.1.0
Version: $version
Licence: Free
Description: An NFS server.
 Moonfish allows you to share files with other computers, either other
 platforms such as Linux, or RISC OS when combined with Sunfish.
 Moonfish supports both the NFS2 and NFS3 protocols, over UDP
 or TCP connections, and has partial support for NFS4.
};

close OUT;

